### ISSUE TITLE
Increasing volume at max makes it go to 0

### ISSUE THREAD

**Issue by christian-nguyen** [ShyykoSerhiy/vscode-spotify#15]
Unsure if this is intentionally or not but if you're at max volume and then try to increase it it'll just go back to 0.

**Comment by ShyykoSerhiy** [comment]
should be fixed in https://github.com/andrehaveman/spotify-node-applescript/blob/master/lib/spotify-node-applescript.js#L18 (need to check for max(100, sound volume + 10)) and in 
https://github.com/andrehaveman/spotify-node-applescript/blob/master/lib/spotify-node-applescript.js#L18 (need to check for min(0, sound volume - 10))

**Comment by ShyykoSerhiy** [comment]
waiting for to be merged https://github.com/andrehaveman/spotify-node-applescript/pull/34

**Comment by duttaditya18** [comment]
@ShyykoSerhiy It was merged! Can the problem be fixed now?

**Comment by ShyykoSerhiy** [comment]
@duttaditya18 sure

**Comment by ShyykoSerhiy** [comment]
Fixed in 2.3.1

**Comment by duttaditya18** [comment]
@ShyykoSerhiy Thank you so much! ❤️
