### ISSUE TITLE
Doesn't play well with debug session

### ISSUE THREAD

**Issue by perlun** [ShyykoSerhiy/vscode-spotify#33]
I wonder if this is intentional or not, but the "back/stop/forward" buttons get placed before any VS Code debug session information, and then the song title etc gets placed _after_ the debug session information:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/630613/37826870-dcb01638-2e9d-11e8-9027-d0b0c79cd2c8.png">

I think it would make perhaps more sense if all the information was contained, but I don't know - are there good reasons for the current behavior?

**Comment by ShyykoSerhiy** [comment]
Yeah, VSCode uses priority system for placement of StatusBar item's. Higher values of priority mean the item should be shown more to the left. 
Priority for each button in this extension is calculated as 
[spotify.priorytyBase](https://github.com/ShyykoSerhiy/vscode-spotify/blob/master/package.json#L186) + [spotify.\<buttonName\>Priority](https://github.com/ShyykoSerhiy/vscode-spotify/blob/master/package.json#L191)
you can see this at [code](https://github.com/ShyykoSerhiy/vscode-spotify/blob/master/src/config/SpotifyConfig.ts#L13) .
Sometimes it can conflict with different extensions that add other StatusBar items (because you cannot possibly know priority values of all possible extensions). The only way to 'fix' this is to change [spotify.priorytyBase](https://github.com/ShyykoSerhiy/vscode-spotify/blob/master/package.json#L186) property. By default it's 30, but 0 does the trick apparently.
<img width="1440" alt="spotify" src="https://user-images.githubusercontent.com/1106995/37848336-22893c32-2eaa-11e8-911d-cb9bb1171dad.png">
