### ISSUE TITLE
1.26 - vscode-spotify: This functionality is not supported on this platform.

### ISSUE THREAD

**Issue by Katolus** [ShyykoSerhiy/vscode-spotify#48]
It seems that for Windows this plugin is no longer supported for 1.26 vsCode update. Is there any plan to solve this? I really enjoy this extension. Can I help in any way?

**Comment by icemouton** [comment]
I'm pretty sure the author knows already since he is the one who deprecated spotilocal which windows and linux integrations where dependent on.

see https://github.com/ShyykoSerhiy/spotilocal/issues/7#issuecomment-416002808

However for linux I can suggest using spotify-cli which works like a charm to control and could implement almost all current commands.

**Comment by ShyykoSerhiy** [comment]
@icemouton on linux it already should work. I use dbus on linux.

**Comment by ShyykoSerhiy** [comment]
@Katolus support is coming back on windows this week. see https://github.com/ShyykoSerhiy/vscode-spotify/issues/42#issuecomment-416394222 for more details. 

P.S. closing this issue as it's a dup of #42

**Comment by Katolus** [comment]
@ShyykoSerhiy thanks! Looking forward to seeing it back.
