### ISSUE TITLE
[Feature] Focus on song

### ISSUE THREAD

**Issue by durdevic** [ShyykoSerhiy/vscode-spotify#56]
The clicking on song title on the bottom (notification bar) to focus it in the plugin list on the left side

**Comment by icemouton** [comment]
Not trying to hijack this issue, but since my request is also related to clicking on the track name, this might give you an idea on how to implement it. 

My request is to be able to click the song title to toggle play/pause, that way I can have a minimal setup with no buttons at all... 

So maybe if you implement song title click, it could be a configurable mode like "focus" and "playPauseToggle" and "showLyrics" and whatever else that button could do... like I said just a thought and not trying to derail from @durdevic suggestion.
