### ISSUE TITLE
No active device found

### ISSUE THREAD

**Issue by troyerta** [ShyykoSerhiy/vscode-spotify#74]
I keep getting this on my Windows machine, and didn't see an issue for it anywhere. 

![image](https://user-images.githubusercontent.com/9409684/48782002-c93ee700-eca2-11e8-8bab-7db1b7bb3e75.png)

**Comment by MarcSerret51** [comment]
Me too in Linux Mint

**Comment by Andresdiaz16** [comment]
So after sometime I came across the "solution" well atleast for me, an its that the Spotify app, like the desktop app needs to be open in order for it to work properly.

**Comment by ShyykoSerhiy** [comment]
Fix is coming in release with the ability to select 'Device' to play on (Like Amazon Echo or phone or whatever)

**Comment by Alynva** [comment]
No more updates?

**Comment by danielrcoates** [comment]
This shouldn't be a bug, but a feature request for a notice saying you must have an active Spotify application to be able to use the plugin

**Comment by theo123490** [comment]
I've opened my spotify app, but I still get this error. I am using windows 10.

**Comment by Lephi0** [comment]
> I've opened my spotify app, but I still get this error. I am using windows 10.

Try playing a son from spotify app. VsCode worked after that for me.

**Comment by theo123490** [comment]
> 
> 
> > I've opened my spotify app, but I still get this error. I am using windows 10.
> 
> Try playing a son from spotify app. VsCode worked after that for me.

It worked, thankyou

**Comment by troyerta** [comment]
This just might be the best way to keep the extension working..

**Comment by Lephi0** [comment]
Glad I could help. :)

**Comment by 7ellipsis** [comment]
I was having the same issue and a workaround this issue is sending the device id with the play request URL. The problem is when sending request to the API it does not find any active device and hence the error, which is bad because if a device is asking a call then it is active and the API should understand that.
When from another spotify client the current device is selected and song is played, it works because  the current device id active status is set true. You can do the same with your request. Just give the device id as the current device it, which will set it to active and will play the song.
**https://api.spotify.com/v1/me/player/play?device_id="+this._device_id**
Worked for me. Hope this helps.

**Comment by Nauj-Montes** [comment]
Vs-code spotify is just an API, it's not an application itself, It doen't run natively on vscode, it's more like a controller, if you have the web player or the app running, and you play a song through the extension, what will play the song is not Vscode 😒, it will be the app or the web player, soooo, personally I just stick with the app cause I'm not saving any resources with the extension🤷🏽‍♂️.
